engines:
  csslint:
    enabled: false
  duplication:
    enabled: false
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: true
    checks:
      max-statements:
        enabled: false
  fixme:
    enabled: true
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- "**.css"
- "**.woff2"
- "**.ttf"
- "**.ico"
- "**.txt"
- "**.md"
- "**.json"
- "**.png"
- "**.jpg
- "**.jpeg"
- "**.wav"
- "**.*db"
- test/**/*
- http/js/translations.js
- http/js/vendor/*

